import Head from 'next/head'

import { Inter } from 'next/font/google'
import { BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillTwitterCircle,AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import Image from "next/image";
import design from '../../public/design.png';
import code from '../../public/code.png';
import consultancy from '../../public/consulting.png';
import hi from "../../public/dev-ed-wave.png";
import web1 from '../../public/web1.png'
import web2 from '../../public/web2.png'
import web3 from '../../public/web3.png'
import web4 from '../../public/web4.png'
import web5 from '../../public/web5.png'
import web6 from '../../public/web6.png'
import {useState} from 'react'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const [darkMode, setDarkMode ] = useState(false)

  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Mikias Aytenfisu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md-p-10 dark:bg-gray-900'>
              <section className=" min-h-screen">
                <nav className='py-2 pt-5 mb-12 flex justify-between'>
                  <h1 className="text-xl "> <span className='dark:text-white'>Developed by</span>  <span className="text-teal-700">Mikias</span> </h1>
                  <ul className='flex item-center'>
                    <li className="dark:text-white"><BsFillMoonStarsFill  onClick = {() => setDarkMode(!darkMode)} className="cursor-pointer"/> </li>
                    <li>
                      <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 ml-4 px-4 py-2 text-white rounded-lg">Resume</a>
                    </li>
                  </ul>
                </nav>
               
               <div className="text-center p-10 ">
                <h2 className="text-5xl py-1 text-teal-600 font-medium">Mikias Aytenfisu</h2>
                <h3 className="text-2xl py-2 dark:text-white">Designer, Developer and Data Analyst</h3>
                <p className="text-md py-2 leading-8 dark:text-white">Full stack web app developer and a junior data analyst.</p>
               </div>
               <div className="text-5xl flex justify-center gap-16 py-1 dark:text-white">
                    <AiFillGithub />
                    <AiFillTwitterCircle />
                    <AiFillLinkedin />
                 
                    
               </div>

               <div className="relative mx-auto mt-10 bg-gradient-to-b from-teal-500  rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96">
                    <Image src = {hi} layout="fill" objectFit='cover'/>
               </div>
              </section>



<section className="mt-10">
  <div className="my-5 text-center ">
    <h3 className="text-3xl py-1 dark:text-teal-200">Services I offer</h3>
    <p className="text-md py-2 leading-8 text-gray-800 text-center dark:text-white">
      Since the beginning of my journey as a developer I have built full stack applications using the <span className='text-teal-500'>MEAN 
        </span>  stack and I am currently building  <span className='text-teal-500'>a MERN </span>stack applicaion.
    </p>
  </div>

  <div className="lg:flex gap-10 ">
    <div className="flex items-center p-4 shadow-lg mb-3 rounded-lg flex-col text-center dark:bg-white">
      <Image src={design} width={100} height={100}/>
      <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
      <h4 className='py-2'>Elegant and up to date web design that suit your need</h4>
      <h4 className="py-4 text-teal-700">Design tools I use </h4>
      <p className="py-1">Photoshop</p>
      <p className="py-1">Figma</p>
      <p className="py-1">Illustrator</p>
    </div>
    <div className="flex items-center p-4 shadow-lg mb-3 rounded-lg flex-col text-center dark:bg-white">
      <Image src={code} width={100} height={100}/>
      <h3 className="text-lg font-medium pt-8 pb-2">Coding</h3>
      <h4 className='py-2'>Building Full Stack Applications </h4>
      <h4 className="py-4 text-teal-700">Programming Lanaguages I Use</h4>
      <p className="py-1">React</p>
      <p className="py-1">Node</p>
      <p className="py-1">MongoDB</p>
    </div>
    <div className="flex items-center p-4 shadow-lg mb-3 rounded-lg flex-col text-center dark:bg-white">
      <Image src={consultancy} width={100} height={100}/>
      <h3 className="text-lg font-medium pt-8 pb-2">Data Analysis</h3>
      <h4 className='py-2'>Offer bussiness consultancy by helping them make data driven decisions </h4>
      <h4 className="py-4 text-teal-700">Data Analysis tools</h4>
      <p className="py-1">Python</p>
      <p className="py-1">SQL</p>
      <p className="py-1">Google Sheets</p>
    </div>
  </div>
</section>
<section>
  <h3 className="text-3xl py-3 text-center text-teal-700">Portfolio</h3>
  <p className="text-md py-2 leading-8 text-gray-800 text-center dark:text-white">
      I have not done any freelance jobs yet. But I have the skill to build full stack web applications. 
      I have done many of my projects using <span className="text-teal-800">
         MEAN and MERN stack.
        </span>
  </p>
  <div className="flex flex-col md:flex-row md:flex-wrap gap-5">
    <div className="lg:basis-1/4 flex-1 md:basis-1/3   ">
      <Image src = {web1} className="rounded-lg object-cover" />
    </div>
    <div className="lg:basis-1/4 flex-1 md:basis-1/3   ">
      <Image src = {web2} className="rounded-lg object-cover" width={"100%"} height="100%" layout="responsive" />
    </div>    <div className="lg:basis-1/4 flex-1 md:basis-1/3  ">
      <Image src = {web3} className="rounded-lg object-cover" width={"100%"} height="100%" layout="responsive" />
    </div>    <div className="lg:basis-1/4 flex-1 md:basis-1/3  ">
      <Image src = {web4} className="rounded-lg object-cover" width={"100%"} height="100%" layout="responsive" />
    </div>    <div className="lg:basis-1/4 flex-1 md:basis-1/3  ">
      <Image src = {web5} className="rounded-lg object-cover" width={"100%"} height="100%" layout="responsive" />
    </div>    <div className="lg:basis-1/4 flex-1 md:basis-1/3  ">
      <Image src = {web6} className="rounded-lg object-cover" width={"100%"} height="100%" layout="responsive" />
    </div>
  </div>
</section>


 </main>


    </div>
  )
}
